### ISSUE TITLE
One more patch release for compat on MappedArrays

### ISSUE THREAD

**Issue by dehann** [JuliaImages/ImageQualityIndexes.jl#30]
Hi @johnnychen94 , thanks for help earlier with patch release on JuliaImages/ImageDraw.jl#48 but that uncovered a second compat issue here.  I see the fix was already done (i.e. MappedArrays was already removed from direct dependencies) but the existing tag still restricted to 0.2:
https://github.com/JuliaImages/ImageQualityIndexes.jl/blob/f409456c33d33781dffdceb11d8b065acbba8ffb/Project.toml#L20

Would it be possible to do a patch release here too please?

------

```julia
┌ Error: Pkg.Resolve.ResolverError("Unsatisfiable requirements detected for package ImageQualityIndexes [2996bd0c]:
 ImageQualityIndexes [2996bd0c] log:
 ├─possible versions are: [0.1.0-0.1.4, 0.2.0] or uninstalled
 ├─restricted by compatibility requirements with MappedArrays [dbb5928d] to versions: uninstalled
 │ └─MappedArrays [dbb5928d] log:
 │   ├─possible versions are: [0.1.0, 0.2.0-0.2.2, 0.3.0] or uninstalled
 │   └─restricted to versions 0.3.0 by an explicit requirement, leaving only versions 0.3.0
 └─restricted by compatibility requirements with Images [916415d5] to versions: [0.1.3-0.1.4, 0.2.0] — no versions left
   └─Images [916415d5] log:
     ├─possible versions are: [0.17.3, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.2, 0.21.0-0.21.1, 0.22.0-0.22.5, 0.23.0-0.23.3] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.17.3, 0.18.0, 0.19.0-0.19.3, 0.20.0-0.20.2, 0.21.0-0.21.1, 0.22.0-0.22.5, 0.23.0-0.23.3]
     └─restricted by compatibility requirements with MappedArrays [dbb5928d] to versions: 0.23.0-0.23.3 or uninstalled, leaving only versions: 0.23.0-0.23.3
       └─MappedArrays [dbb5928d] log: see above", nothing)
```

**Comment by johnnychen94** [comment]
Sorry for the delay, it's near the end of the semester so I'm a little bit busy here. I've bumped the version, hope this is the last one.

**Comment by dehann** [comment]
Thanks again, no worry on timing, just noting for whenever your someone else might get a chance.  Good luck with finishing the semester!

I tend to find compat issues since some of our packages have large dependency sets.  Perhaps I could help by sending PRs for CompatHelper to some of the base Images.jl packages?

**Comment by johnnychen94** [comment]
Of course, feel free to submit PRs!
